#pragma config(Sensor, dgtl1,  bottomStage,    sensorDigitalIn)
#pragma config(Sensor, dgtl2,  midStage,       sensorDigitalIn)
#pragma config(Sensor, dgtl3,  topStage,       sensorDigitalIn)
#pragma config(Sensor, dgtl5,  bumpLeft,       sensorDigitalIn)
#pragma config(Sensor, dgtl7,  clamp,          sensorDigitalOut)
#pragma config(Sensor, dgtl10, bumpRight,      sensorDigitalIn)
#pragma config(Sensor, dgtl11, pusher,         sensorDigitalOut)
#pragma config(Motor,  port2,           frontLeftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           backLeftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           frontRightMotor, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           backRightMotor, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           elevatorMotor, tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                              - Dual Joystick Control with 4 Motors -                               *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses both the Left and the Right joysticks to run the robot using "tank control".    *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing both right-side motors (ports 2 and 3) in the "Motors and Sensors Setup" is       *|
|*        needed with the "VEX Tumbler" model, but may not be needed for all robot configurations.    *|
|*    2)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    3)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]                [Type]                [Description]                   *|
|*    Motor Port 2        frontRightMotor       VEX 3-wire module     Right side motor                *|
|*    Motor Port 3        backRightMotor        VEX 3-wire module     Right side motor                *|
|*    Motor Port 4        frontLefttMotor       VEX 3-wire module     Left side motor                 *|
|*    Motor Port 5        backLeftMotor         VEX 3-wire module     Left side motor                 *|
\*----------------------------------------------------------------------------------------------------*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	//int waitcont = 0;
	int topSpeedPercent = 40;
	int topSpeedTurnPercent = 20;
	SensorValue[pusher] = 0;
	SensorValue[clamp] = 0;
	int push_loop_count = 0;
	bool push_active = false;

  while(1 == 1)
  {
  	//Cubic
  	//For arcade drive
  	//int rightStickCubed = vexRT[Ch1]*vexRT[Ch1]*vexRT[Ch1]/16129;

  	//For tank drive
  	//int rightStickCubed = vexRT[Ch2]*vexRT[Ch2]*vexRT[Ch2]/16129;

  	//int leftStickCubed = vexRT[Ch3]*vexRT[Ch3]*vexRT[Ch3]/16129;
		//Linear
   	int rightStickCubed = vexRT[Ch1];
  	int leftStickCubed = vexRT[Ch3];

  	if(vexRT[Btn5U]){
  		topSpeedPercent = 60;
  		topSpeedTurnPercent = 30;
  	}else{
  		topSpeedPercent = 40;
  		topSpeedTurnPercent = 20;
	  }

  	rightStickCubed = (rightStickCubed * topSpeedTurnPercent)/100;
  	leftStickCubed = (leftStickCubed * topSpeedPercent)/100;
  /* Tank Drive
  	//Right side of the robot is controlled by the right joystick, Y-axis
    motor[frontRightMotor] = vexRT[Ch2];
    motor[backRightMotor]  = vexRT[Ch2];
    //Left side of the robot is controlled by the left joystick, Y-axis
    motor[frontLeftMotor] = vexRT[Ch3];
    motor[backLeftMotor]  = vexRT[Ch3];
   */

   //Arcade drive
    motor[frontLeftMotor]  = leftStickCubed + rightStickCubed;
    motor[frontRightMotor] = leftStickCubed - rightStickCubed;
    motor[backLeftMotor]  = leftStickCubed + rightStickCubed;
    motor[backRightMotor] = leftStickCubed - rightStickCubed;

/*
    if(vexRT[Btn5U]){
    	motor[elevatorMotor] = 63;
    }else if(vexRT[Btn5D]){
    	motor[elevatorMotor] = -63;
    }else{
    	motor[elevatorMotor] = 0;
	  }
*/
    if(vexRT[Btn5UXmtr2] && SensorValue[topStage] == 0){
    	motor[elevatorMotor] = 63;
    }else if(vexRT[Btn5DXmtr2] && SensorValue[bottomStage] == 0){
    	motor[elevatorMotor] = -63;
    }else{
    	motor[elevatorMotor] = 0;
	  }
		//The arm
	  if(vexRT[Btn6UXmtr2]  || vexRT[Btn8RXmtr2]){
	  	SensorValue[clamp] = 1;
		}else if(vexRT[Btn6DXmtr2] || ((SensorValue[bumpLeft] == 0) && (SensorValue[bumpRight] == 0))){
			SensorValue[clamp] = 0;
		}

		//The thing to push the cube
		if(vexRT[Btn8UXmtr2]){
	  	SensorValue[pusher] = 1;
		}
		else if(vexRT[Btn8DXmtr2]  || vexRT[Btn8RXmtr2]){
			SensorValue[pusher] = 0;
		}

		if(vexRT[Btn8RXmtr2]){
			push_active = true;
		  push_loop_count =20000;
		}

		if(push_active){
			if(push_loop_count == 0){
				SensorValue[pusher] = 1;
				push_active = false;
			}else{
				push_loop_count--;
			}
		}
}
}


//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
